-- ValidX Supabase core schema
-- Run this in the Supabase SQL editor or with `supabase db push`.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('business', 'tester', 'admin')),
  email text not null,
  auth_method text not null default 'supabase',
  first_name text not null default 'New',
  last_name text not null default 'User',
  company text,
  industry text,
  company_size text,
  school text,
  major text,
  age integer,
  status text not null default 'active' check (status in ('active', 'suspended', 'banned')),
  created_at timestamptz not null default now()
);

create unique index if not exists profiles_email_idx on public.profiles (lower(email));
create index if not exists profiles_role_idx on public.profiles (role);

create table if not exists public.experiments (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  assumption text not null,
  type text not null,
  tier text not null check (tier in ('quick-test', 'deep-dive', 'full-study')),
  budget integer not null check (budget > 0),
  reach integer not null check (reach > 0),
  status text not null default 'active' check (status in ('draft', 'active', 'completed', 'archived')),
  paid_with text,
  payment_ref text,
  created_at timestamptz not null default now()
);

create index if not exists experiments_owner_idx on public.experiments (owner_id);
create index if not exists experiments_status_created_idx on public.experiments (status, created_at desc);

create table if not exists public.experiment_claims (
  id bigint generated by default as identity primary key,
  experiment_id bigint not null references public.experiments(id) on delete cascade,
  tester_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'claimed' check (status in ('claimed', 'submitted', 'cancelled')),
  created_at timestamptz not null default now(),
  unique (experiment_id, tester_id)
);

create index if not exists experiment_claims_tester_idx on public.experiment_claims (tester_id, status);

create table if not exists public.submissions (
  id bigint generated by default as identity primary key,
  experiment_id bigint not null references public.experiments(id) on delete cascade,
  tester_id uuid not null references public.profiles(id) on delete cascade,
  notes text not null,
  files_json jsonb not null default '[]'::jsonb,
  payout integer not null default 0,
  status text not null default 'submitted' check (status in ('submitted', 'approved', 'rejected')),
  admin_note text,
  created_at timestamptz not null default now(),
  unique (experiment_id, tester_id)
);

create index if not exists submissions_experiment_idx on public.submissions (experiment_id);
create index if not exists submissions_tester_idx on public.submissions (tester_id, status);

create table if not exists public.payouts (
  id bigint generated by default as identity primary key,
  tester_id uuid not null references public.profiles(id) on delete cascade,
  amount integer not null check (amount > 0),
  method text not null check (method in ('stripe', 'paypal')),
  status text not null default 'pending' check (status in ('pending', 'processing', 'paid', 'failed')),
  reference text,
  created_at timestamptz not null default now(),
  paid_at timestamptz
);

create index if not exists payouts_tester_idx on public.payouts (tester_id, status);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  action text not null,
  details jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.current_profile_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid() limit 1
$$;

create or replace function public.current_profile_status()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select status from public.profiles where id = auth.uid() limit 1
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_profile_role() = 'admin', false)
$$;

create or replace function public.available_balance_for(tester uuid)
returns integer
language sql
stable
security definer
set search_path = public
as $$
  with earned as (
    select coalesce(sum(payout), 0)::integer as total
    from public.submissions
    where tester_id = tester
      and status in ('submitted', 'approved')
  ),
  claimed as (
    select coalesce(sum(amount), 0)::integer as total
    from public.payouts
    where tester_id = tester
      and status in ('pending', 'processing', 'paid')
  )
  select greatest(0, earned.total - claimed.total)::integer
  from earned, claimed
$$;

create or replace function public.set_submission_payout()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  experiment_budget integer;
begin
  select budget into experiment_budget
  from public.experiments
  where id = new.experiment_id;

  if experiment_budget is null then
    raise exception 'Experiment not found';
  end if;

  new.payout := round(experiment_budget * 0.3)::integer;
  return new;
end;
$$;

drop trigger if exists submissions_set_payout on public.submissions;
create trigger submissions_set_payout
before insert on public.submissions
for each row execute function public.set_submission_payout();

alter table public.profiles enable row level security;
alter table public.experiments enable row level security;
alter table public.experiment_claims enable row level security;
alter table public.submissions enable row level security;
alter table public.payouts enable row level security;
alter table public.audit_log enable row level security;

drop policy if exists "Profiles are visible to self, related businesses, and admins" on public.profiles;
create policy "Profiles are visible to self, related businesses, and admins"
on public.profiles for select
to authenticated
using (
  id = auth.uid()
  or public.is_admin()
  or exists (
    select 1
    from public.submissions s
    join public.experiments e on e.id = s.experiment_id
    where s.tester_id = profiles.id
      and e.owner_id = auth.uid()
  )
);

drop policy if exists "Users can create their public profile" on public.profiles;
create policy "Users can create their public profile"
on public.profiles for insert
to authenticated
with check (
  id = auth.uid()
  and role in ('business', 'tester')
  and status = 'active'
);

drop policy if exists "Admins can manage profiles" on public.profiles;
create policy "Admins can manage profiles"
on public.profiles for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Visible experiments" on public.experiments;
create policy "Visible experiments"
on public.experiments for select
to authenticated
using (
  status = 'active'
  or owner_id = auth.uid()
  or public.is_admin()
);

drop policy if exists "Businesses can create experiments" on public.experiments;
create policy "Businesses can create experiments"
on public.experiments for insert
to authenticated
with check (
  owner_id = auth.uid()
  and public.current_profile_role() = 'business'
  and public.current_profile_status() = 'active'
);

drop policy if exists "Business owners can update experiments" on public.experiments;
create policy "Business owners can update experiments"
on public.experiments for update
to authenticated
using (owner_id = auth.uid() or public.is_admin())
with check (owner_id = auth.uid() or public.is_admin());

drop policy if exists "Testers can read own claims" on public.experiment_claims;
create policy "Testers can read own claims"
on public.experiment_claims for select
to authenticated
using (tester_id = auth.uid() or public.is_admin());

drop policy if exists "Testers can claim active experiments" on public.experiment_claims;
create policy "Testers can claim active experiments"
on public.experiment_claims for insert
to authenticated
with check (
  tester_id = auth.uid()
  and public.current_profile_role() = 'tester'
  and public.current_profile_status() = 'active'
  and exists (
    select 1 from public.experiments e
    where e.id = experiment_id and e.status = 'active'
  )
);

drop policy if exists "Testers can remove own claims" on public.experiment_claims;
create policy "Testers can remove own claims"
on public.experiment_claims for delete
to authenticated
using (tester_id = auth.uid() or public.is_admin());

drop policy if exists "Visible submissions" on public.submissions;
create policy "Visible submissions"
on public.submissions for select
to authenticated
using (
  tester_id = auth.uid()
  or public.is_admin()
  or exists (
    select 1 from public.experiments e
    where e.id = submissions.experiment_id
      and e.owner_id = auth.uid()
  )
);

drop policy if exists "Testers can submit active experiments" on public.submissions;
create policy "Testers can submit active experiments"
on public.submissions for insert
to authenticated
with check (
  tester_id = auth.uid()
  and public.current_profile_role() = 'tester'
  and public.current_profile_status() = 'active'
  and length(trim(notes)) >= 10
  and exists (
    select 1 from public.experiments e
    where e.id = experiment_id
      and e.status = 'active'
  )
);

drop policy if exists "Admins can update submissions" on public.submissions;
create policy "Admins can update submissions"
on public.submissions for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Visible payouts" on public.payouts;
create policy "Visible payouts"
on public.payouts for select
to authenticated
using (tester_id = auth.uid() or public.is_admin());

drop policy if exists "Testers can request available cashouts" on public.payouts;
create policy "Testers can request available cashouts"
on public.payouts for insert
to authenticated
with check (
  tester_id = auth.uid()
  and public.current_profile_role() = 'tester'
  and public.current_profile_status() = 'active'
  and status = 'pending'
  and amount >= 5
  and amount <= public.available_balance_for(auth.uid())
);

drop policy if exists "Admins can update payouts" on public.payouts;
create policy "Admins can update payouts"
on public.payouts for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can read audit log" on public.audit_log;
create policy "Admins can read audit log"
on public.audit_log for select
to authenticated
using (public.is_admin());

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.profiles to authenticated;
grant select, insert, update, delete on public.experiments to authenticated;
grant select, insert, update, delete on public.experiment_claims to authenticated;
grant select, insert, update, delete on public.submissions to authenticated;
grant select, insert, update, delete on public.payouts to authenticated;
grant select, insert on public.audit_log to authenticated;
grant usage, select on all sequences in schema public to authenticated;
